# List of extensions to load
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  # TargetRubyVersion: '3.0.1'
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'bin/bundle'

Rails/I18nLocaleTexts:
    Enabled: false 

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    # - lib/loggable_activity/hooks.rb
Metrics/AbcSize:
  Exclude:
    - lib/loggable_activity/encryption.rb
    - lib/loggable_activity/update_payloads_builder.rb
    - db/migrate/*_loggable_activity_tables.loggable_activity.rb
