fetch_actor_name_from: full_name
Demo::City:
  route: /demo/cities/:id
  fetch_record_name_from: name
  loggable_attrs:
    - name
    - country
  auto_log:
    - create
    - update
    - destroy
  public_attrs:
    - name
  relations:
    - has_many: :demo_addresses
      fetch_record_name_from: full_address
      route: show_demo_city_demo_address 
      model: Demo::Address
      loggable_attrs:
        - street
        - postal_code
    - has_many: :users
      route: show_user
      model: User
      loggable_attrs:
        - first_name
        - last_name
User: 
  fetch_record_name_from: full_name
  route: /demo/users/:id
  loggable_attrs: 
    - first_name
    - last_name 
    - age 
    - email
    - user_type 
  public_attrs:
    - first_name
  auto_log:
    - create
    - update
    - destroy
  relations:
    - has_one: :demo_user_profile
      route: show_user_profile
      model: Demo::UserProfile 
      loggable_attrs:
        - sex
        - religion
      public_attrs:
        - sex
    - belongs_to: :demo_address
      route: show_demo_address
      model: Demo::Address
      loggable_attrs:
        - street
        - postal_code
      public_attrs:
        - street
    - belongs_to: :demo_club
      route: show_demo_club
      model: Demo::Club
      loggable_attrs:
        - name
Demo::Address: 
  fetch_record_name_from: full_address
  route: /demo/addresses/:id
  actor_display_name: email
  loggable_attrs:
    - street
    - postal_code
  public_attrs:
    - street
  auto_log:
    - create
    - update
    - destroy
Demo::Club: 
  fetch_record_name_from: name 
  route: /demo/clubs/:id
  loggable_attrs: 
    - name
  public_attrs:
    - name
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :demo_address
      model: Demo::Address
      loggable_attrs:
        - street
        - postal_code
      public_attrs:
        - street
Demo::Journal: 
  fetch_record_name_from: title 
  route: demo/journals/:id
  loggable_attrs: 
    - title 
    - body
    - state
  public_attrs:
    - title
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :doctor
      model: User 
      route: show_doctor
      data_owner: false 
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - user_type
      public_attrs:
        - first_name
    - belongs_to: :patient
      route: show_patient
      model: User 
      data_owner: true
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - age 
        - user_type
      public_attrs:
        - first_name
Demo::UserProfile: 
  loggable_attrs:
    - sex
    - religion
  public_attrs:
    - sex