User: 
  record_display_name: full_name
  route: demo_user_path
  loggable_attrs: 
    - first_name
    - last_name 
    - age 
    - email
    - user_type 
  auto_log:
    - create
    - update
    - destroy
  relations:
    - has_one: :demo_user_profile
      model: Demo::UserProfile 
      loggable_attrs:
        - sex
        - religion
    - belongs_to: :demo_address
      route: demo_address_path
      model: Demo::Address
      loggable_attrs:
        - street
        - country
        - postal_code
    - belongs_to: :demo_club
      model: Demo::Club
      loggable_attrs:
        - name
Demo::Address: 
  record_display_name: full_address
  route: demo_address_path
  actor_display_name: email
  loggable_attrs:
    - street
    - country
    - postal_code
  auto_log:
    - create
    - update
    - destroy
Demo::Product:
  loggable_attrs:
    - name
    - description
    - price
    - part_number
  auto_log:
    - create
    - update
    - destroy
Demo::Club: 
  record_display_name: name 
  route: demo_club_path
  loggable_attrs: 
    - name
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :demo_address
      model: Demo::Address
      loggable_attrs:
        - street
        - country
        - postal_code
Demo::Journal: 
  record_display_name: title 
  route: demo_journal_path
  loggable_attrs: 
    - title 
    - body
    - state
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :doctor
      model: User 
      route: demo_user_path
      data_owner: false 
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - user_type
    - belongs_to: :patient
      route: demo_user_path
      model: User 
      data_owner: true
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - age 
        - user_type
Demo::UserProfile: 
  loggable_attrs:
    - sex
    - religion