fetch_current_user_name_from: full_name
current_user_model_name: User
Demo::City:
  route: show_demo_city
  fetch_record_name_from: name
  loggable_attrs:
    - name
    - country
  auto_log:
    - create
    - update
    - destroy
  relations:
    - has_many: :demo_addresses
      fetch_record_name_from: full_address
      route: show_demo_city_demo_address 
      model: Demo::Address
      loggable_attrs:
        - street
        - postal_code
    - has_many: :users
      route: show_user
      model: User
      loggable_attrs:
        - first_name
        - last_name
User: 
  fetch_record_name_from: full_name
  route: show_user
  loggable_attrs: 
    - first_name
    - last_name 
    - age 
    - email
    - user_type 
  auto_log:
    - create
    - update
    - destroy
  relations:
    - has_one: :demo_user_profile
      route: show_user_profile
      model: Demo::UserProfile 
      loggable_attrs:
        - sex
        - religion
    - belongs_to: :demo_address
      route: show_demo_address
      model: Demo::Address
      loggable_attrs:
        - street
        - postal_code
    - belongs_to: :demo_club
      route: show_demo_club
      model: Demo::Club
      loggable_attrs:
        - name
Demo::Address: 
  fetch_record_name_from: full_address
  route: show_demo_address
  actor_display_name: email
  loggable_attrs:
    - street
    - postal_code
  auto_log:
    - create
    - update
    - destroy

Demo::Club: 
  fetch_record_name_from: name 
  route: show_demo_club
  loggable_attrs: 
    - name
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :demo_address
      model: Demo::Address
      loggable_attrs:
        - street
        - postal_code
Demo::Journal: 
  fetch_record_name_from: title 
  route: show_demo_journal
  loggable_attrs: 
    - title 
    - body
    - state
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :doctor
      model: User 
      route: show_doctor
      data_owner: false 
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - user_type
    - belongs_to: :patient
      route: show_patient
      model: User 
      data_owner: true
      loggable_attrs:
        - first_name 
        - last_name 
        - email 
        - age 
        - user_type
Demo::UserProfile: 
  route: show_user
  loggable_attrs:
    - sex
    - religion