# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/demo/cities', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Demo::City. As you add validations to Demo::City, be sure to
  # adjust the attributes here as well.

  let(:user) { create(:user) }

  let(:valid_attributes) do
    { name: 'New York', country: 'USA' }
  end

  let(:invalid_attributes) do
    { name: nil, country: nil }
  end

  before do
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Demo::City.create! valid_attributes
      get demo_cities_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      city = Demo::City.create! valid_attributes
      get demo_city_url(city)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_demo_city_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      city = Demo::City.create! valid_attributes
      get edit_demo_city_url(city)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Demo::City' do
        expect do
          post demo_cities_url, params: { demo_city: valid_attributes }
        end.to change(Demo::City, :count).by(1)
      end

      it 'redirects to the created demo_city' do
        post demo_cities_url, params: { demo_city: valid_attributes }
        expect(response).to redirect_to(demo_cities_url)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Demo::City' do
        expect do
          post demo_cities_url, params: { demo_city: invalid_attributes }
        end.to change(Demo::City, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post demo_cities_url, params: { demo_city: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { name: 'Paris', country: 'France' }
      end

      it 'updates the requested demo_city' do
        city = Demo::City.create! valid_attributes
        patch demo_city_url(city), params: { demo_city: new_attributes }
        city.reload
        expect(city.name).to eq(new_attributes[:name])
      end

      it 'redirects to the demo_city' do
        city = Demo::City.create! valid_attributes
        patch demo_city_url(city), params: { demo_city: new_attributes }
        city.reload
        expect(response).to redirect_to(demo_cities_url)
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        city = Demo::City.create! valid_attributes
        patch demo_city_url(city), params: { demo_city: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested demo_city' do
      city = Demo::City.create! valid_attributes
      expect do
        delete demo_city_url(city)
      end.to change(Demo::City, :count).by(-1)
    end

    it 'redirects to the demo_cities list' do
      city = Demo::City.create! valid_attributes
      delete demo_city_url(city)
      expect(response).to redirect_to(demo_cities_url)
    end
  end
end
